# Generated by Django 4.2.13 on 2024-06-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('seating_plan', models.CharField(choices=[('Festival', 'Festival'), ('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('CAT 3', 'CAT 3'), ('CAT 4', 'CAT 4')], max_length=20)),
                ('seat_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
            ],
        ),
    ]
