# Generated by Django 4.2.13 on 2024-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seating_plan',
            field=models.TextField(),
        ),
    ]
