# Generated by Django 4.2.13 on 2024-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_ticket_email_alter_ticket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
